import React, { useEffect } from "react";

import {Link} from 'react-router-dom'
import "./welcome.css";

const Welcome = () => {
  const positiveStatements = [
    "Today is going to be a great day!",
    "You are capable of amazing things!",
    "Believe in yourself!",
    "Every day is a fresh start.",
    "You are stronger than you think.",
    "You have the power to create change.",
    "Positivity is a choice. Choose it!",
    "You are worthy of love and respect.",
    "Focus on the good in every situation.",
    "Today is a new opportunity to be your best self.",
    "You are a wonderful person.",
    "Embrace the challenges of today.",
    "Smile, it's a new day!",
    "You are destined for greatness.",
    "Radiate positivity.",
    "Your potential is limitless.",
    "Take a deep breath and start again.",
    "You are loved more than you know.",
    "You are an inspiration.",
    "Your journey is unique and beautiful.",
    "Keep moving forward.",
    "Today is filled with possibilities.",
    "Cherish every moment.",
    "Your smile brightens the world.",
    "You can handle anything that comes your way.",
    "Live in the moment.",
    "Spread kindness wherever you go.",
    "You make a difference.",
    "You have the power to make today amazing.",
    "You are enough just as you are.",
    "You are a light in the world.",
    "Every step you take is a step forward.",
    "Your hard work will pay off.",
    "Be kind to yourself.",
    "Today is a gift, cherish it.",
    "You have a beautiful soul.",
    "Stay positive and good things will happen.",
    "Your dreams are within reach.",
    "You are a blessing to those around you.",
    "Keep your head up.",
    "Your positivity is contagious.",
    "You are capable of incredible things.",
    "Believe in the magic of today.",
    "Your happiness matters.",
    "You are doing great.",
    "Take time to enjoy the little things.",
    "You are a gift to the world.",
    "You are appreciated.",
    "Stay strong, you got this.",
    "Be yourself, you are amazing.",
    "Focus on what makes you happy.",
    "You have the power to make someone smile.",
    "You are important.",
    "You are a warrior.",
    "Keep pushing forward.",
    "You bring joy to others.",
    "Your positive attitude is a strength.",
    "You are a ray of sunshine.",
    "Believe in the beauty of your dreams.",
    "You are unique and special.",
    "Today is your day.",
    "You are a positive influence.",
    "Keep believing in yourself.",
    "You have a heart of gold.",
    "Your positivity makes a difference.",
    "You are unstoppable.",
    "You are amazing just the way you are.",
    "Stay true to yourself.",
    "Your optimism is inspiring.",
    "You are capable of great things.",
    "Keep smiling, it's contagious.",
    "You are a beacon of light.",
    "Every day is a new adventure.",
    "You are loved and cherished.",
    "Stay hopeful and strong.",
    "You are brave and courageous.",
    "You are full of potential.",
    "Keep your spirit high.",
    "You are a wonderful friend.",
    "Embrace today with open arms.",
    "You are full of creativity.",
    "Your smile is your best accessory.",
    "You are a true gem.",
    "Today is a new chance to shine.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you.",
    "Your positivity makes a difference.",
    "Stay hopeful and strong.",
    "You are a true gem.",
    "Your smile is your best accessory.",
    "Keep smiling, it's contagious.",
    "You are unstoppable.",
    "You are a source of inspiration.",
    "Your kindness is powerful.",
    "Stay positive and spread love.",
    "You are a beautiful person.",
    "Your energy is infectious.",
    "Keep dreaming big.",
    "You are a breath of fresh air.",
    "You are a shining star.",
    "Stay positive and keep moving forward.",
    "You are a gift to the world.",
    "Your positivity is your strength.",
    "Keep shining, the world needs your light.",
    "You are a true blessing.",
    "Your kindness makes the world a better place.",
    "You are a beautiful soul.",
    "Stay positive, stay happy.",
    "You are a ray of hope.",
    "Your smile lights up the room.",
    "You are full of potential.",
    "Keep your dreams alive.",
    "You are an amazing person.",
    "Stay positive, good things are coming.",
    "You are a wonderful person.",
    "Your optimism is a gift.",
    "You are a true inspiration.",
    "Stay positive and believe in yourself.",
    "You are a ray of sunshine.",
    "Your smile is your best asset.",
    "Keep shining, the world needs your light.",
    "You are a blessing to those around you",
  ];
  // alert(positiveStatements.length);
  // 942
  

  return (
    <div className="wbody">
      <div class="blog-slider">
        <div class="blog-slider__wrp swiper-wrapper">
          <div class="blog-slider__item swiper-slide">
            <div class="blog-slider__img">
              <img
                src="https://res.cloudinary.com/muhammederdem/image/upload/q_60/v1535759872/kuldar-kalvik-799168-unsplash.webp"
                alt=""
              />
            </div>
            <div class="blog-slider__content">
              <span class="blog-slider__code">26 December 2019</span>
              <div class="blog-slider__title">Lorem Ipsum Dolor</div>
              <div class="blog-slider__text">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                Recusandae voluptate repellendus magni illo ea animi?{" "}
              </div>
              <Link  class="blog-slider__button">
                READ MORE
              </Link>
            </div>
          </div>
          <div class="blog-slider__item swiper-slide">
            <div class="blog-slider__img">
              <img
                src="https://res.cloudinary.com/muhammederdem/image/upload/q_60/v1535759871/jason-leung-798979-unsplash.webp"
                alt=""
              />
            </div>
            <div class="blog-slider__content">
              <span class="blog-slider__code">26 December 2019</span>
              <div class="blog-slider__title">Lorem Ipsum Dolor2</div>
              <div class="blog-slider__text">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                Recusandae voluptate repellendus magni illo ea animi?
              </div>
              <Link  class="blog-slider__button">
                READ MORE
              </Link>
            </div>
          </div>

          <div class="blog-slider__item swiper-slide">
            <div class="blog-slider__img">
              <img
                src="https://res.cloudinary.com/muhammederdem/image/upload/q_60/v1535759871/alessandro-capuzzi-799180-unsplash.webp"
                alt=""
              />
            </div>
            <div class="blog-slider__content">
              <span class="blog-slider__code">26 December 2019</span>
              <div class="blog-slider__title">Lorem Ipsum Dolor</div>
              <div class="blog-slider__text">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                Recusandae voluptate repellendus magni illo ea animi?
              </div>
              <Link  class="blog-slider__button">
                READ MORE
              </Link>
            </div>
          </div>
        </div>
        <div class="blog-slider__pagination"></div>
      </div>
    </div>
  );
};

export default Welcome;
