// src/Marquee.js
import React, {useEffect,useState} from "react";
// import "./Marquee.css";
const messages = [
  "Join Codar Institute and master Web Development today!",
  "Transform your career with AI courses at Codar Institute.",
  "Become a Project Management expert with Codar Institute.",
  "Learn Product Design from industry leaders at Codar Institute.",
  "Unlock the power of Data Analysis at Codar Institute.",
  "Master UI/UX Design with Codar Institute.",
  "Secure your future with Cybersecurity courses at Codar Institute.",
  "Enhance your skills with DevOps training at Codar Institute.",
  "Join Codar Institute for hands-on Web Development training.",
  "Advance your career with AI and Machine Learning at Codar.",
  "Get certified in Project Management with Codar Institute.",
  "Create stunning designs with our Product Design course.",
  "Turn data into insights with our Data Analysis programs.",
  "Design intuitive interfaces with our UI/UX courses.",
  "Protect digital assets with Cybersecurity training at Codar.",
  "Streamline operations with our DevOps courses.",
  "Codar Institute: Your gateway to a tech career.",
  "Learn the latest in Web Development at Codar Institute.",
  "Stay ahead in AI with Codar Institute's cutting-edge courses.",
  "Manage projects like a pro with Codar Institute's training.",
  "Design products that users love with Codar Institute.",
  "Harness the power of data with Codar Institute.",
  "Create user-friendly designs with UI/UX courses at Codar.",
  "Defend against cyber threats with Codar Institute.",
  "Optimize your workflows with Codar Institute's DevOps courses.",
  "Codar Institute: Shaping tech experts in Africa, Nigeria.",
  "Jumpstart your tech career with Codar Institute.",
  "Learn from industry experts at Codar Institute.",
  "Join Codar Institute for comprehensive tech training.",
  "Achieve your career goals with Codar Institute.",
  "Codar Institute: Where innovation meets education.",
  "Master front-end and back-end development with Codar.",
  "Explore the future of AI with Codar Institute.",
  "Lead successful projects with training from Codar.",
  "Design innovative products with Codar Institute.",
  "Analyze data like a pro with Codar Institute.",
  "Create seamless user experiences with UI/UX courses.",
  "Stay safe online with Cybersecurity training at Codar.",
  "Codar Institute: Your path to a tech-savvy future.",
  "Upgrade your skills with DevOps courses at Codar.",
  "Learn to build dynamic websites at Codar Institute.",
  "Advance in AI and ML with Codar Institute.",
  "Excel in Project Management with Codar Institute.",
  "Create impactful product designs with Codar Institute.",
  "Become a data expert with Codar Institute.",
  "Craft beautiful user interfaces with UI/UX courses.",
  "Guard against cyber threats with Codar Institute.",
  "Enhance your DevOps skills with Codar Institute.",
  "Codar Institute: Empowering the next generation of tech leaders.",
  "Build your tech career with Codar Institute.",
  "Join Codar Institute and become a Web Development pro.",
  "Dive into AI with Codar Institute's specialized courses.",
  "Manage projects effectively with Codar Institute's training.",
  "Design products that stand out with Codar Institute.",
  "Turn data into actionable insights with Codar Institute.",
  "Create intuitive designs with UI/UX training at Codar.",
  "Stay protected online with Cybersecurity courses at Codar.",
  "Optimize development processes with Codar Institute's DevOps training.",
  "Codar Institute: Leading tech education in Africa, Nigeria.",
  "Achieve tech excellence with Codar Institute.",
  "Learn Web Development from the best at Codar Institute.",
  "Stay on the cutting edge of AI with Codar Institute.",
  "Become a Project Management expert with Codar.",
  "Design innovative products with courses at Codar Institute.",
  "Master data analysis techniques with Codar Institute.",
  "Create engaging user experiences with UI/UX courses at Codar.",
  "Defend digital infrastructures with Cybersecurity training.",
  "Streamline your operations with DevOps courses at Codar.",
  "Codar Institute: Pioneering tech training in Africa.",
  "Enhance your tech skills with Codar Institute.",
  "Join Codar Institute for world-class Web Development training.",
  "Explore the possibilities of AI with Codar Institute.",
  "Lead projects to success with Codar Institute's training.",
  "Design user-centered products with Codar Institute.",
  "Unlock data insights with Codar Institute.",
  "Create visually appealing interfaces with UI/UX courses.",
  "Protect against cyber attacks with Codar Institute.",
  "Optimize software development with DevOps courses at Codar.",
  "Codar Institute: Your partner in tech education.",
  "Build a successful tech career with Codar Institute.",
  "Join Codar Institute for expert-led Web Development courses.",
  "Advance your AI knowledge with Codar Institute.",
  "Become a certified Project Manager with Codar Institute.",
  "Learn to design top-notch products with Codar Institute.",
  "Analyze and interpret data effectively with Codar Institute.",
  "Craft user-friendly designs with UI/UX courses at Codar.",
  "Stay ahead of cyber threats with Cybersecurity training.",
  "Enhance your DevOps capabilities with Codar Institute.",
  "Codar Institute: Shaping the future of tech in Africa.",
  "Excel in tech with Codar Institute's comprehensive training.",
  "Master Web Development at Codar Institute.",
  "Stay current with AI advancements at Codar Institute.",
  "Manage projects efficiently with Codar Institute's training.",
  "Design impactful products with Codar Institute.",
  "Turn data into gold with Codar Institute.",
  "Create stunning user experiences with UI/UX courses at Codar.",
  "Guard your digital world with Cybersecurity courses at Codar.",
  "Optimize your development pipeline with DevOps training at Codar.",
  "Codar Institute: Innovating tech education in Africa.",
  "Build your dream tech career with Codar Institute.",
  "Join Codar Institute for unparalleled Web Development training.",
  "Dive deep into AI with Codar Institute's specialized courses.",
  "Lead projects to success with Codar's Project Management training.",
  "Design user-centric products with Codar Institute.",
  "Master the art of data analysis with Codar Institute.",
  "Create intuitive user interfaces with UI/UX training at Codar.",
  "Protect your digital assets with Cybersecurity training at Codar.",
  "Streamline your development processes with DevOps courses.",
  "Codar Institute: Empowering tech enthusiasts in Africa.",
  "Enhance your tech career with Codar Institute.",
  "Join Codar Institute and excel in Web Development.",
  "Stay ahead in AI with Codar Institute's cutting-edge courses.",
  "Manage projects like a pro with Codar's Project Management training.",
  "Design innovative products with Codar Institute.",
  "Analyze data like a professional with Codar Institute.",
  "Create seamless user experiences with UI/UX courses at Codar.",
  "Stay safe online with Cybersecurity training at Codar.",
  "Optimize your workflows with DevOps training at Codar.",
  "Codar Institute: Leading the way in tech education.",
  "Achieve your tech goals with Codar Institute.",
  "Master Web Development with Codar Institute's expert training.",
  "Explore the future of AI with Codar Institute.",
  "Lead successful projects with Codar Institute's training.",
  "Design products that users love with Codar Institute.",
  "Harness the power of data with Codar Institute.",
  "Create user-friendly designs with UI/UX courses at Codar.",
  "Defend against cyber threats with Codar Institute's Cybersecurity training.",
  "Enhance your DevOps skills with Codar Institute's courses.",
  "Codar Institute: Your path to tech success.",
  "Build your tech future with Codar Institute.",
  "Join Codar Institute for hands-on Web Development training.",
  "Advance in AI and Machine Learning with Codar Institute.",
  "Get certified in Project Management with Codar Institute.",
  "Create stunning product designs with Codar Institute.",
  "Turn data into insights with Codar Institute's Data Analysis courses.",
  "Design intuitive interfaces with Codar Institute's UI/UX courses.",
  "Protect digital assets with Codar Institute's Cybersecurity training.",
  "Streamline operations with Codar Institute's DevOps training.",
  "Codar Institute: Shaping the tech leaders of tomorrow.",
  "Jumpstart your tech career with Codar Institute.",
  "Learn from industry experts at Codar Institute.",
  "Join Codar Institute for comprehensive tech training.",
  "Achieve your career goals with Codar Institute.",
  "Codar Institute: Where innovation meets education.",
  "Master front-end and back-end development with Codar.",
  "Explore the future of AI with Codar Institute.",
  "Lead successful projects with training from Codar.",
  "Design innovative products with Codar Institute.",
  "Analyze data like a pro with Codar Institute.",
  "Create seamless user experiences with UI/UX courses.",
  "Stay safe online with Cybersecurity training at Codar.",
  "Codar Institute: Your path to a tech-savvy future.",
  "Upgrade your skills with DevOps courses at Codar.",
  "Learn to build dynamic websites at Codar Institute.",
  "Advance in AI and ML with Codar Institute.",
  "Excel in Project Management with Codar Institute.",
  "Create impactful product designs with Codar Institute.",
  "Become a data expert with Codar Institute.",
  "Craft beautiful user interfaces with UI/UX courses.",
  "Guard against cyber threats with Codar Institute",
  "Enhance your DevOps skills with Codar Institute.",
  "Codar Institute: Empowering the next generation of tech leaders.",
  "Build your tech career with Codar Institute.",
  "Join Codar Institute and become a Web Development pro.",
  "Dive into AI with Codar Institute's specialized courses.",
  "Manage projects effectively with Codar Institute's training.",
  "Design products that stand out with Codar Institute.",
  "Turn data into actionable insights with Codar Institute.",
  "Create intuitive designs with UI/UX training at Codar.",
  "Stay protected online with Cybersecurity courses at Codar.",
  "Optimize development processes with Codar Institute's DevOps training.",
  "Codar Institute: Leading tech education in Africa, Nigeria.",
  "Achieve tech excellence with Codar Institute.",
  "Learn Web Development from the best at Codar Institute.",
  "Stay on the cutting edge of AI with Codar Institute.",
  "Become a Project Management expert with Codar.",
  "Design innovative products with courses at Codar Institute.",
  "Master data analysis techniques with Codar Institute.",
  "Create engaging user experiences with UI/UX courses at Codar.",
  "Defend digital infrastructures with Cybersecurity training.",
  "Streamline your operations with DevOps courses at Codar.",
  "Codar Institute: Pioneering tech training in Africa.",
  "Enhance your tech skills with Codar Institute.",
  "Join Codar Institute for world-class Web Development training.",
  "Explore the possibilities of AI with Codar Institute.",
  "Lead projects to success with Codar Institute's training.",
  "Design user-centered products with Codar Institute.",
  "Unlock data insights with Codar Institute.",
  "Create visually appealing interfaces with UI/UX courses.",
  "Protect against cyber attacks with Codar Institute.",
  "Optimize software development with DevOps courses at Codar.",
  "Codar Institute: Innovating tech education in Africa.",
  "Build your dream tech career with Codar Institute.",
  "Join Codar Institute for unparalleled Web Development training.",
  "Dive deep into AI with Codar Institute's specialized courses.",
  "Lead projects to success with Codar's Project Management training.",
  "Design user-centric products with Codar Institute.",
  "Master the art of data analysis with Codar Institute.",
  "Create intuitive user interfaces with UI/UX training at Codar.",
  "Protect your digital assets with Cybersecurity training at Codar.",
  "Streamline your development processes with DevOps courses.",
  "Codar Institute: Empowering tech enthusiasts in Africa.",
  "Enhance your tech career with Codar Institute.",
  "Join Codar Institute and excel in Web Development.",
  "Stay ahead in AI with Codar Institute's cutting-edge courses.",
  "Manage projects like a pro with Codar's Project Management training.",
  "Design innovative products with Codar Institute.",
  "Analyze data like a professional with Codar Institute.",
  "Create seamless user experiences with UI/UX courses at Codar.",
  "Stay safe online with Cybersecurity training at Codar.",
  "Optimize your workflows with DevOps training at Codar.",
  "Codar Institute: Leading the way in tech education.",
  "Achieve your tech goals with Codar Institute.",
  "Master Web Development with Codar Institute's expert training.",
  "Explore the future of AI with Codar Institute.",
  "Lead successful projects with Codar Institute's training.",
  "Design products that users love with Codar Institute.",
  "Harness the power of data with Codar Institute.",
  "Create user-friendly designs with UI/UX courses at Codar.",
  "Defend against cyber threats with Codar Institute's Cybersecurity training.",
  "Enhance your DevOps skills with Codar Institute's courses.",
  "Codar Institute: Your path to tech success.",
  "Build your tech future with Codar Institute.",
  "Join Codar Institute for hands-on Web Development training.",
  "Advance in AI and Machine Learning with Codar Institute.",
  "Get certified in Project Management with Codar Institute.",
  "Create stunning product designs with Codar Institute.",
  "Turn data into insights with Codar Institute's Data Analysis courses.",
  "Design intuitive interfaces with Codar Institute's UI/UX courses.",
  "Protect digital assets with Codar Institute's Cybersecurity training.",
  "Streamline operations with Codar Institute's DevOps training.",
  "Codar Institute: Shaping the tech leaders of tomorrow.",
  "Jumpstart your tech career with Codar Institute.",
  "Learn from industry experts at Codar Institute.",
  "Join Codar Institute for comprehensive tech training.",
  "Achieve your career goals with Codar Institute.",
  "Codar Institute: Where innovation meets education.",
  "Master front-end and back-end development with Codar.",
  "Explore the future of AI with Codar Institute.",
  "Lead successful projects with training from Codar.",
  "Design innovative products with Codar Institute.",
  "Analyze data like a pro with Codar Institute.",
  "Create seamless user experiences with UI/UX courses.",
  "Stay safe online with Cybersecurity training at Codar.",
  "Codar Institute: Your path to a tech-savvy future.",
  "Upgrade your skills with DevOps courses at Codar.",
  "Learn to build dynamic websites at Codar Institute.",
  "Advance in AI and ML with Codar Institute.",
  "Excel in Project Management with Codar Institute.",
  "Create impactful product designs with Codar Institute.",
  "Become a data expert with Codar Institute.",
  "Craft beautiful user interfaces with UI/UX courses.",
  "Guard against cyber threats with Codar Institute.",
  "Enhance your DevOps skills with Codar Institute.",
  "Codar Institute: Empowering the next generation of tech leaders.",
  "Build your tech career with Codar Institute.",
  "Join Codar Institute and become a Web Development pro.",
  "Dive into AI with Codar Institute's specialized courses.",
  "Manage projects effectively with Codar Institute's training.",
  "Design products that stand out with Codar Institute.",
  "Turn data into actionable insights with Codar Institute.",
  "Create intuitive designs with UI/UX training at Codar.",
  "Stay protected online with Cybersecurity courses at Codar.",
  "Optimize development processes with Codar Institute's DevOps training.",
  "Codar Institute: Leading tech education in Africa, Nigeria.",
  "Achieve tech excellence with Codar Institute.",
  "Learn Web Development from the best at Codar Institute.",
  "Stay on the cutting edge of AI with Codar Institute.",
  "Become a Project Management expert with Codar.",
  "Design innovative products with courses at Codar Institute.",
  "Master data analysis techniques with Codar Institute.",
  "Create engaging user experiences with UI/UX courses at Codar.",
  "Defend digital infrastructures with Cybersecurity training.",
  "Streamline your operations with DevOps courses at Codar.",
  "Codar Institute: Pioneering tech training in Africa.",
  "Enhance your tech skills with Codar Institute.",
  "Join Codar Institute for world-class Web Development training.",
  "Explore the possibilities of AI with Codar Institute.",
  "Lead projects to success with Codar Institute's training.",
  "Design user-centered products with Codar Institute.",
  "Unlock data insights with Codar Institute.",
  "Create visually appealing interfaces with UI/UX courses.",
  "Protect against cyber attacks with Codar Institute.",
  "Optimize software development with DevOps courses at Codar.",
  "Codar Institute: Innovating tech education in Africa.",
  "Build your dream tech career with Codar Institute.",
  "Join Codar Institute for unparalleled Web Development training.",
  "Dive deep into AI with Codar Institute's specialized courses.",
  "Lead projects to success with Codar's Project Management training.",
  "Design user-centric products with Codar Institute.",
  "Master the art of data analysis with Codar Institute.",
  "Create intuitive user interfaces with UI/UX training at Codar.",
  "Protect your digital assets with Cybersecurity training at Codar.",
  "Streamline your development processes with DevOps courses.",
  "Codar Institute: Empowering tech enthusiasts in Africa.",
  "Enhance your tech career with Codar Institute.",
  "Join Codar Institute and excel in Web Development.",
  "Stay ahead in AI with Codar Institute's cutting-edge courses.",
  "Manage projects like a pro with Codar's Project Management training.",
  "Design innovative products with Codar Institute.",
  "Analyze data like a professional with Codar Institute.",
  "Create seamless user experiences with UI/UX courses at Codar.",
  "Stay safe online with Cybersecurity training at Codar.",
  "Optimize your workflows with DevOps training at Codar.",
  "Codar Institute: Leading the way in tech education.",
  "Achieve your tech goals with Codar Institute.",
  "Master Web Development with Codar Institute's expert training.",
  "Explore the future of AI with Codar Institute.",
  "Lead successful projects with Codar Institute's training.",
  "Design products that users love with Codar Institute.",
  "Harness the power of data with Codar Institute.",
  "Create user-friendly designs with UI/UX courses at Codar.",
  "Defend against cyber threats with Codar Institute's Cybersecurity training.",
  "Enhance your DevOps skills with Codar Institute's courses.",
  "Codar Institute: Your path to tech success.",
  "Build your tech future with Codar Institute.",
  "Join Codar Institute for hands-on Web Development training.",
  "Advance in AI and Machine Learning with Codar Institute.",
  "Get certified in Project Management with Codar Institute.",
  "Create stunning product designs with Codar Institute.",
  "Turn data into insights with Codar Institute's Data Analysis courses.",
  "Design intuitive interfaces with Codar Institute's UI/UX courses.",
  "Protect digital assets with Codar Institute's Cybersecurity training.",
  "Streamline operations with Codar Institute's DevOps training.",
  "Codar Institute: Shaping the tech leaders of tomorrow.",
  "Jumpstart your tech career with Codar Institute.",
  "Learn from industry experts at Codar Institute.",
  "Join Codar Institute for comprehensive tech training.",
  "Achieve your career goals with Codar Institute.",
  "Codar Institute: Where innovation meets education.",
  "Master front-end and back-end development with Codar.",
  "Explore the future of AI with Codar Institute.",
  "Lead successful projects with training from Codar.",
  "Design innovative products with Codar Institute.",
  "Analyze data like a pro with Codar Institute.",
  "Create seamless user experiences with UI/UX courses.",
  "Stay safe online with Cybersecurity training at Codar.",
  "Codar Institute: Your path to a tech-savvy future.",
  "Upgrade your skills with DevOps courses at Codar.",
  "Learn to build dynamic websites at Codar Institute.",
  "Advance in AI and ML with Codar Institute.",
  "Excel in Project Management with Codar Institute.",
  "Create impactful product designs with Codar Institute.",
  "Become a data expert with Codar Institute.",
  "Craft beautiful user interfaces with UI/UX courses.",
  "Guard against cyber threats with Codar Institute.",
  "Enhance your DevOps skills with Codar Institute.",
  "Codar Institute: Empowering the next generation of tech leaders.",
  "Build your tech career with Codar Institute.",
  "Join Codar Institute and become a Web Development pro.",
  "Dive into AI with Codar Institute's specialized courses.",
  "Manage projects effectively with Codar Institute's training.",
  "Design products that stand out with Codar Institute.",
  "Turn data into actionable insights with Codar Institute.",
  "Create intuitive designs with UI/UX training at Codar.",
  "Stay protected online with Cybersecurity courses at Codar.",
  "Optimize development processes with Codar Institute's DevOps training.",
  "Codar Institute: Leading tech education in Africa, Nigeria.",
  "Achieve tech excellence with Codar Institute.",
  "Learn Web Development from the best at Codar Institute.",
  "Stay on the cutting edge of AI with Codar Institute.",
  "Become a Project Management expert with Codar.",
  "Design innovative products with courses at Codar Institute.",
  "Master data analysis techniques with Codar Institute.",
  "Create engaging user experiences with UI/UX courses at Codar.",
  "Defend digital infrastructures with Cybersecurity training.",
  "Streamline your operations with DevOps courses at Codar.",
  "Codar Institute: Pioneering tech training in Africa.",
  "Enhance your tech skills with Codar Institute.",
  "Join Codar Institute for world-class Web Development training.",
  "Explore the possibilities of AI with Codar Institute.",
  "Lead projects to success with Codar Institute's training.",
  "Design user-centered products with Codar Institute.",
  "Unlock data insights with Codar Institute.",
  "Create visually appealing interfaces with UI/UX courses.",
  "Protect against cyber attacks with Codar Institute."
];

// alert(messages.length)


const Marquee = () => {
    const [currentMessage, setCurrentMessage] = useState("");

    useEffect(() => {
      // Function to pick a random message
      const pickRandomMessage = () => {
        const randomIndex = Math.floor(Math.random() * messages.length);
        setCurrentMessage(messages[randomIndex]);
      };

      // Pick an initial message
      pickRandomMessage();

      // Set an interval to pick a new message every 30 seconds
      const intervalId = setInterval(pickRandomMessage, 30000);

      // Clean up the interval on component unmount
      return () => clearInterval(intervalId);
    }, [messages]);
  return (
    <footer className="footerm">
      <div className="marquee">
        <div className="marquee-inner">
          <p className="text-ldanger">{currentMessage}</p>
        </div>
      </div>
    </footer>
  );
};

export default Marquee;
